### ISSUE TITLE
Blazepe_Core + Bot Discord Z Nagrodą Od Firka :D

### ISSUE THREAD

**Issue by GerLook** [AdiPol1359/mcbe-starterpack#3]
[CORE.zip](https://github.com/AdiPol1359/mcbe-starterpack/files/9183551/CORE.zip)
[hardBot.zip](https://github.com/AdiPol1359/mcbe-starterpack/files/9183553/hardBot.zip)

**Comment by AdiPol1359** [comment]
Dostosuj się do rozkładu plików.
